apiVersion: v1
kind: Namespace
metadata:
  name: prowler

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prowler
  namespace: prowler

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prowler
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prowler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prowler
subjects:
- kind: ServiceAccount
  name: prowler
  namespace: prowler

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: prowler
  namespace: prowler
spec:
  schedule: "0 1 * * *"  # Run daily at 1 AM
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: prowler
          containers:
          - name: prowler
            image: toniblyx/prowler:latest
            args:
            - "--compliance"
            - "cis"
            - "-M"
            - "csv,json"
          restartPolicy: OnFailure
