name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: your-ec2-instance-ip
        USER: ec2-user
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
          # Install K3s
          curl -sfL https://get.k3s.io | sh -
          
          # Wait for K3s to be ready
          until kubectl get nodes; do sleep 5; done
          
          # Install Helm
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
          
          # Create namespaces
          kubectl create namespace checkov
          kubectl create namespace prowler
          kubectl create namespace cert-manager
          
          # Install Prowler using the yaml file from the repo
          kubectl apply -f ~/prowler.yaml -n prowler
          
          # Install Checkov
          kubectl apply -f https://raw.githubusercontent.com/bridgecrewio/checkov/main/kubernetes/checkov-job.yaml -n checkov
          
          # Install cert-manager
          kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.15.1/cert-manager.crds.yaml
          helm repo add jetstack https://charts.jetstack.io --force-update
          helm install cert-manager jetstack/cert-manager --namespace cert-manager --version v1.15.1
          
          # Verify installations
          kubectl get namespaces
          kubectl get pods -n checkov
          kubectl get pods -n prowler
          kubectl get pods -n cert-manager
          helm list -A
        '
