name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Copy prowler.yaml to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: 35.175.132.153
        USER: ubuntu
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        scp -o StrictHostKeyChecking=no -i private_key prowler.yaml ${USER}@${HOST}:~/prowler.yaml

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: 35.175.132.153
        USER: ubuntu
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
          # Install K3s
          curl -sfL https://get.k3s.io | sudo sh -
          
          # Set KUBECONFIG environment variable
          export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
          sudo chmod 644 $KUBECONFIG
          
          # Wait for K3s to be ready
          until sudo kubectl get nodes; do sleep 5; done
          
          # Install Helm
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | sudo bash
          
          # Create namespaces
          sudo kubectl create namespace checkov --dry-run=client -o yaml | sudo kubectl apply -f -
          sudo kubectl create namespace prowler --dry-run=client -o yaml | sudo kubectl apply -f -
          sudo kubectl create namespace cert-manager --dry-run=client -o yaml | sudo kubectl apply -f -
          
          # Install Prowler using the yaml file from the repo
          sudo kubectl apply -f ~/prowler.yaml -n prowler
          
          # Install Checkov
          sudo kubectl apply -f https://raw.githubusercontent.com/bridgecrewio/checkov/main/kubernetes/checkov-job.yaml -n checkov
          
          # Install cert-manager
                    # Verify installations
          sudo kubectl get namespaces
          sudo kubectl get pods -n checkov
          sudo kubectl get pods -n prowler
          sudo kubectl get pods -n cert-manager
          sudo helm list -A
          sudo kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.15.1/cert-manager.crds.yaml
          sudo helm repo add jetstack https://charts.jetstack.io --force-update
          sudo helm upgrade --install cert-manager jetstack/cert-manager --namespace cert-manager --version v1.15.1
          
          # Verify installations
          sudo kubectl get namespaces
          sudo kubectl get pods -n checkov
          sudo kubectl get pods -n prowler
          sudo kubectl get pods -n cert-manager
          sudo helm list -A
        '

